version: '2'

services:
  server:
    image: golang:alpine
    container_name: goreact
    # ports:
    #   - 8080:8080
    labels:
      - "traefik.port=8080"
    volumes:
      - ./server:/go/src/server
    working_dir: /go/src/server
    command: go run main.go
    depends_on: 
      - build
    networks: 
      - goreact
  build:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
      - ./server/view:/usr/src/app/build
    command: yarn build
  dev:
    image: node:alpine
    container_name: dev-goreact
    ports: 
      - 3000:3000
    labels:
      - "traefik.port=3000"
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    command: yarn start
    networks: 
      - goreact
networks:
  goreact:
