version: '2'

services:
  app:
    image: golang:alpine
    container_name: goreact
    labels:
      - "traefik.port=8080"
    volumes:
      - ./:/go/src/app
      - ./web/build:/go/src/app/web
    working_dir: /go/src/app
    command: go run main.go
    links: 
      - db
    depends_on: 
      - build
    networks: 
      - goreact
  db:
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=go-react-db
    networks:
      - goreact
  build:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    command: yarn build
  dev:
    image: node:alpine
    container_name: dev-goreact
    ports: 
      - 3000:3000
    labels:
      - "traefik.port=3000"
    working_dir: /usr/src/app
    volumes:
      - ./web:/usr/src/app
    command: yarn start
    networks: 
      - goreact
networks:
  goreact:
